/*Subconsultas I*/
/*NOTAMOS QUE ES UN SELECT DONDE DE OTRO SELECT*/
SELECT NOMBREARTÍCULO, SECCIÓN FROM PRODUCTOS WHERE PRECIO >(SELECT  AVG(PRECIO) FROM PRODUCTOS)
/*USANDO OPERADOR ALL
ACA LE DECIMOS QUE ME DE TODOS LOS QUE SEAN MAYORES A LA LISTA DE SUBCONSULTA*/
SELECT * FROM PRODUCTOS WHERE PRECIO >ALL (SELECT PRECIO FROM PRODUCTOS WHERE SECCIÓN ="CERÁMICA")
/*EN EL CASO DE ANY DEVUELVE MAYOR A CUARQUIERA DE LA LISTA DE LA SUBCONSULTA
EN EL CASO ANTERIOR SOLO TOMABA EL MAYO DE LA LISTA DE LA SUBCONSULTA*/

SELECT * FROM PRODUCTOS WHERE PRECIO >ANY (SELECT PRECIO FROM PRODUCTOS WHERE SECCIÓN ="CERÁMICA")
/*CASO PARECIDO AL ANTERIOR*/
SELECT * FROM PRODUCTOS WHERE PRECIO> ANY (SELECT PRECIO FROM PRODUCTOS WHERE SECCIÓN ="JUGUETERIA")
