/*Subconsultas II*/
/*BUSCAR ALTICULOS DONDE LOS PEDIDOS SEAN MAYORES A 17 UNIDADES Y ESTEN DENTRO
DE LA SUBCONSULTA*/
SELECT NOMBREARTÍCULO,PRECIO FROM `PRODUCTOS_MASTER` WHERE `CÓDIGO CLIENTE` 
IN (SELECT `CÓDIGO CLIENTE`  FROM `PEDIDOS2` WHERE  UNIDADES>17)
/*EN ESTE CASO ORDEMOS POR CODIGO CLIENTE
SI USAMOS EL COMANDO IN NO HACE FALTA QUE LAS TABLAS ESTEN RELACIONADAS,
SE OBTIENE EL MISMO RESULTADO CON INNER JOIN PERO LA SINTAXY ES MAS LARGA
*/
SELECT NOMBREARTÍCULO,PRECIO, `CÓDIGO CLIENTE`  FROM `PRODUCTOS_MASTER`
WHERE `CÓDIGO CLIENTE` IN (SELECT `CÓDIGO CLIENTE`  FROM `PEDIDOS2` WHERE  UNIDADES>17) ORDER BY `CÓDIGO CLIENTE`

/**/
SELECT * FROM `CLIENTES2`WHERE `CÓDIGO CLIENTE`  NOT IN (SELECT `CÓDIGO CLIENTE` FROM `PEDIDOS3` WHERE `FORMA DE PAGO`='TARJETA')
/* NOTAR QUE LA SUB-CONSULTA NO TENGAS CAMPOS NULL PUESTO GENERARA UN ERROR EN LA CONSULTA*/
SELECT * FROM `CLIENTES2`WHERE `CÓDIGO CLIENTE`  NOT IN (SELECT `CÓDIGO CLIENTE` FROM PEDIDOS3 WHERE `FORMA DE PAGO`="TARJETA")