/*Consultas de agrupación o totales. y funciones de agregados*/
/* seleccional la col seccion y la suma de los precios de todos los articulos 
agrupandolos por seccion seccion*/
SELECT SECCIÓN, SUM(PRECIO) FROM PRODUCTOS GROUP BY SECCIÓN;
/*ESTA LINEA ARROJA UN ERROR PUESTO NO HAY CAMPO PRECIO EN LA CONSULTA
(NOTA QUE HABLAMOS DE LA CONSULTA Y NO DE LA TABLA)*/
SELECT SECCIÓN, SUM(PRECIO) FROM PRODUCTOS GROUP BY SECCIÓN ORDER BY PRECIO;
/*USANDO UN ASLIAS AS PARA LAS CONSULTA Y ORDENANDO POR EL ALIAS QUE SE 
MONTRARA EN LA CONSULTA SI FUNCIONARA */
SELECT SECCIÓN, SUM(PRECIO) AS SUMA_ARTICULOS FROM PRODUCTOS 
GROUP BY SECCIÓN  ORDER BY SUMA_ARTICULOS;
/*  EN ESTE CASO VEMOS LA MISMA INF SOLO QUE AGREGAMOS EN NOMBRE ARTICULO
NOTA QUE AGREGAMOS NOMBRE ARTICULO EN EL BROUP BY, DE LO CONTRARIO DARIA UN ERROR DE CONSULTA*/
SELECT SECCIÓN, NOMBREARTÍCULO , SUM(PRECIO) AS SUMA_ARTICULOS FROM PRODUCTOS 
GROUP BY SECCIÓN, NOMBREARTÍCULO  ORDER BY SUMA_ARTICULOS;
/* NOTA QUE EN ESTE CASO ESTAMOS UBICANDO LA MEDIA DE LOS PRECION 
DE LA SECCION DEPORTES Y SERAMICA NOTE QUE SE USA EL COMANDO HAVING EN VES DE WHERE PARA 
FILTRAR LA BUSQUEDA
 */
SELECT SECCIÓN, AVG(PRECIO) AS MEDIA_ARTICULOS  FROM PRODUCTOS 
GROUP BY SECCIÓN HAVING SECCIÓN='DEPORTES' OR SECCIÓN='CERÁMICA';
/* EN ESTE CASO ORDENAMOS LA COL MEDIA_ARTICULOS */
SELECT SECCIÓN, AVG(PRECIO) AS MEDIA_ARTICULOS  FROM PRODUCTOS 
GROUP BY SECCIÓN HAVING SECCIÓN='DEPORTES' OR SECCIÓN='CONFECCIÓN'
ORDER BY MEDIA_ARTICULOS;
/* EN ESTE CASO CONTAMOS CUANTOS CLIENTES TENEMOS POR POBLACION*/
SELECT POBLACIÓN, COUNT(CÓDIGOCLIENTE) AS N_CLIENTES FROM CLIENTES
 GROUP BY POBLACIÓN;
 /* UBICAMOS LA SECCION QUE TENGA EL PRECIO MAXIMO DE VENTA*/
 SELECT SECCIÓN, MAX(PRECIO) AS PRECIO_MAX FROM PRODUCTOS WHERE
 SECCIÓN='CONFECCIÒN' GROUP BY SECCIÓN;
/* LA SIGUIENTE LINEA DA ERROR PORQUE LA CLAPSULA WHERE DEBE IR ANTES DE GROUP BY*/
/*
SELECT SECCIÓN, MAX(PRECIO) AS PRECIO_MAX FROM PRODUCTOS 
GROUP BY SECCIÓN WHERE SECCIÓN='CONFECCIÓN';
*/
/* BUSCAMOS EN ARTICULO CON EL PRECIO MAXIMO DE LA SECCION CONFECCION Y SOLO MOSTRAMOS
UN ARTICULO LIMITANDO LA CONSULTA A 1*/
SELECT SECCIÓN, NOMBREARTÍCULO, MAX(PRECIO) AS PRECIO_MAX FROM PRODUCTOS WHERE 
SECCIÓN='CONFECCIÓN' GROUP BY SECCIÓN,NOMBREARTÍCULO/* LIMIT 1;*/;
/* ESTA LINEA ESPECIFICAMOS MEJOR LA CONSULTA PIDIENDO QUE ORDENE LOS PRODUCTOS 
Y ME MUESTRE SOLO EL MAX*/
SELECT SECCIÓN, NOMBREARTÍCULO, MAX(PRECIO) AS PRECIO_MAX FROM 
PRODUCTOS WHERE SECCIÓN='CONFECCIÓN' GROUP BY SECCIÓN,NOMBREARTÍCULO 
ORDER BY PRECIO_MAX  DESC /*LIMIT 1*/;