/*Consultas Multitabla I. O consultas de union*/
/* EN ESTE CASO UNIMOS EL RESULTADO DE LA PRIMERA CONSULTA CON LA SEGUNDA*/ 
SELECT * FROM PRODUCTOS WHERE SECCIÓN="DEPORTES" UNION 
SELECT * FROM ProductosNuevos WHERE SECCIÓN="DEPORTES DE RIESGO"
/**/
SELECT * FROM PRODUCTOS WHERE PRECIO > 500 UNION 
SELECT * FROM ProductosNuevos WHERE SECCIÓN="ALTA COSTURA"
/*UNION MOSTRARA SOLO UN ARTICULO EN CASO QUE EXISTAN FILAS COMPLETAMENTE IGUALES
*/
SELECT * FROM PRODUCTOS WHERE SECCIÓN="DEPORTES" UNION
SELECT * FROM ProductosNuevos
/* EN ESTE CASO LE DECIMOS A LA CONSULTA QUE SI SE REPINTEN REGISTROS
 LOS MUESTRE AMBOS*/
SELECT * FROM PRODUCTOS WHERE SECCIÓN="DEPORTES" UNION ALL
SELECT * FROM ProductosNuevos