/*Consultas de cálculo.*/
/*se pueden implementar calculos matematicos auna columna y luego aplicar un alias
en este caso se le suma un 21% a precio del producto
 */
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, PRECIO*1.21,2 AS MAS_IVA FROM PRODUCTOS;
/* en este caso se usa la funcion RAUND para redondear el valor MAS_IVA en dos desimales*/
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, ROUND(PRECIO*1.21,2) 
AS MAS_IVA FROM PRODUCTOS;
/*EN ESTE CASO APLICAMOS UN DEESCUENTO DE 3$ AL PRECIO DEL ARTICULO*/
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, PRECIO-3 AS DESCUENTO_3USD FROM PRODUCTOS
/**/
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, FECHA FROM PRODUCTOS WHERE SECCIÓN='DEPORTES'
/*EN ESTE CASO VEMOS EN LA CONSULTA UN CAMPO CON EL DIA Y LA HORA ACTUAL*/
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, FECHA, NOW() AS TODAY  FROM PRODUCTOS WHERE SECCIÓN='DEPORTES'
/* CALCULOS CON DATOS TIPO FECHA AGREGAMOS UN CAMPO QUE NOS MUESTRA LOS DIAS DE DIFERENCIA DE CREADO EL PRODUCTO*/ 
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, FECHA, NOW() AS TODAY, DATEDIFF(NOW(),FECHA) AS DIFF_DAY
FROM PRODUCTOS WHERE SECCIÓN='DEPORTES'
/* EN ESTE CASO APLICAMOS UNA FUNCION PARA FORMATEAR LA FECHA A NUESTRA CONVENIENCIA*/
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, FECHA, DATE_FORMAT(NOW(),'%D-%M-%Y') AS TODAY, DATEDIFF(NOW(),FECHA) AS DIFF_DAY
FROM PRODUCTOS WHERE SECCIÓN='DEPORTES'